# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-08-11 08:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20180811_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 11, 8, 6, 19, 986409)),
        ),
    ]
