# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-08-15 08:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20180811_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 15, 8, 21, 12, 775312)),
        ),
    ]
