# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-08-08 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('name', models.CharField(max_length=160)),
                ('slug_name', models.SlugField(max_length=350)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('name', models.CharField(max_length=160)),
                ('slug_name', models.SlugField(max_length=350)),
                ('is_veg', models.BooleanField(default=False, verbose_name='is_veg')),
                ('description', models.TextField()),
                ('time_slot', models.TextField()),
                ('mrp', models.PositiveSmallIntegerField()),
                ('offer_price', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dishes',
            },
        ),
        migrations.CreateModel(
            name='DishImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('name', models.CharField(max_length=160)),
                ('is_veg', models.BooleanField(default=False, verbose_name='is_veg')),
                ('description', models.TextField()),
                ('time_slot', models.TextField()),
                ('mrp', models.PositiveSmallIntegerField()),
                ('offer_price', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dish_images',
            },
        ),
    ]
