# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-08-08 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0002_auto_20180808_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=160, unique=True),
        ),
    ]
