# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-08-11 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0006_dish_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
