# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-08-11 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0007_auto_20180811_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='thumbnail',
            field=models.URLField(blank=True, default='/static/app/admin/assets/images/pexels.jpeg', null=True),
        ),
    ]
